# generated by datamodel-codegen:
#   filename:  drone.json
#   timestamp: 2023-10-14T06:34:52+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class Drone(BaseModel):
    name: str = Field(..., description='Name of the drone')
    model: str = Field(..., description='Model of the drone')
    id: str = Field(..., description='id of the drone')
